spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/overbrain-local
    username: postgres
    password: Engineer6544

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: garayev.elbrus
    password: Engineer6544
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
